# 服务器配置
server:
  host: "0.0.0.0"
  port: "8080"
  jwt_secret: "your-jwt-secret-key"

# 数据库配置
database:
  driver: "mysql"
  host: "localhost"
  port: "3306"
  user: "your-user"
  password: "your-password"
  dbname: "your-dbname"

# Redis配置
redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

# LLM服务配置
llm:
  host: "localhost"
  port: "50051"

# 日志配置
log:
  level: "info"
  path: "./logs" 