// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: llm_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 首先定义消息类型
type GenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Temperature   float32                `protobuf:"fixed32,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxNewTokens  int32                  `protobuf:"varint,3,opt,name=max_new_tokens,json=maxNewTokens,proto3" json:"max_new_tokens,omitempty"`
	TopK          int32                  `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_llm_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GenerateRequest) GetMaxNewTokens() int32 {
	if x != nil {
		return x.MaxNewTokens
	}
	return 0
}

func (x *GenerateRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type GenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_llm_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_llm_service_proto protoreflect.FileDescriptor

const file_llm_service_proto_rawDesc = "" +
	"\n" +
	"\x11llm_service.proto\x12\x03llm\"\x86\x01\n" +
	"\x0fGenerateRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x02R\vtemperature\x12$\n" +
	"\x0emax_new_tokens\x18\x03 \x01(\x05R\fmaxNewTokens\x12\x13\n" +
	"\x05top_k\x18\x04 \x01(\x05R\x04topK\".\n" +
	"\x10GenerateResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse2G\n" +
	"\n" +
	"LLMService\x129\n" +
	"\bGenerate\x12\x14.llm.GenerateRequest\x1a\x15.llm.GenerateResponse\"\x00B\x1eZ\x1cbackend/internal/model/protob\x06proto3"

var (
	file_llm_service_proto_rawDescOnce sync.Once
	file_llm_service_proto_rawDescData []byte
)

func file_llm_service_proto_rawDescGZIP() []byte {
	file_llm_service_proto_rawDescOnce.Do(func() {
		file_llm_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_service_proto_rawDesc), len(file_llm_service_proto_rawDesc)))
	})
	return file_llm_service_proto_rawDescData
}

var file_llm_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_llm_service_proto_goTypes = []any{
	(*GenerateRequest)(nil),  // 0: llm.GenerateRequest
	(*GenerateResponse)(nil), // 1: llm.GenerateResponse
}
var file_llm_service_proto_depIdxs = []int32{
	0, // 0: llm.LLMService.Generate:input_type -> llm.GenerateRequest
	1, // 1: llm.LLMService.Generate:output_type -> llm.GenerateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_llm_service_proto_init() }
func file_llm_service_proto_init() {
	if File_llm_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_service_proto_rawDesc), len(file_llm_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_service_proto_goTypes,
		DependencyIndexes: file_llm_service_proto_depIdxs,
		MessageInfos:      file_llm_service_proto_msgTypes,
	}.Build()
	File_llm_service_proto = out.File
	file_llm_service_proto_goTypes = nil
	file_llm_service_proto_depIdxs = nil
}
